### ISSUE TITLE
Startup crash due to preference loading ID conflation

### ISSUE THREAD

**Issue by danieljennings** [Awful/Awful.apk#648]
I think it will be easier if this is cataloged here, especially if the issue ends up being... interesting, rather than it living in the SA thread, but this is the same thing those guys are seeing.

What I did:
1. Had no Android devtools installed, so I had to install Android Studio and SDK. I only installed SDK 28 (9.0), and it's on incremental version 6. Looks like the gradle files reference 28, so that should be good.
2. Testing against an emulated Pixel 2 XL running Android 9.0.
3. Forked Awful.apk from Github.
4. Checked out the 'develop' branch locally.
5. Opened the stuff in Android Studio and started building.
6. Added secrets.xml and my own Imgur ID to fix that error per the related commit.
7. Built in debug and ran it on the emulator.
8. Startup crash.

I'm going to keep debugging more, right now, but wanted to get this written in case this gets hairy (and Java is probably my like 10th best language at this point).

Here's the crash stack:

`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ferg.awfulapp.debug, PID: 28593
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ferg.awfulapp.debug/com.ferg.awfulapp.ForumsIndexActivity}: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
        at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:326)
        at com.ferg.awfulapp.preferences.AwfulPreferences.getPreference(AwfulPreferences.java:334)
        at com.ferg.awfulapp.preferences.AwfulPreferences.updateValues(AwfulPreferences.java:265)
        at com.ferg.awfulapp.preferences.AwfulPreferences.onSharedPreferenceChanged(AwfulPreferences.java:232)
        at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
        at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:489)
        at com.ferg.awfulapp.preferences.AwfulPreferences.setPreference(AwfulPreferences.java:374)
        at com.ferg.awfulapp.ForumsIndexActivity.showChangelogIfRequired(ForumsIndexActivity.kt:215)
        at com.ferg.awfulapp.ForumsIndexActivity.onCreate(ForumsIndexActivity.kt:96)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
`

If I set a breakpoint on the YouTube preference getter and step inside, I see that it's expecting a boolean (obviously) but getting 10002 out. That 10002 is coming from the last version preference being set:

`mPrefs.setPreference(Keys.LAST_VERSION_SEEN, versionCode)`

Going to do some more debugging now and see that they're at least using different keys to make sure it's not a problem with R somehow.

**Comment by danieljennings** [comment]
After configuring the Android Studio better (or just due to randomness/nondeterminism?) the first exception that I caught (and maybe was missing before) was resource-related, not specifically preference related.

Inside of the actual ResourcesManager::getResources call below, we do see an exception thrown, but I don't think it takes down the application (but debugger is breaking there when I break on exceptions), which is suspicious:

```
    public Resources getResources() {
        if (mResources == null) {
            final String[] splitPaths;
            try {
                splitPaths = getSplitPaths(null);
            } catch (NameNotFoundException e) {
                // This should never fail.
                throw new AssertionError("null split not found");
            }

            mResources = ResourcesManager.getInstance().getResources(null, mResDir,
                    splitPaths, mOverlayDirs, mApplicationInfo.sharedLibraryFiles,
                    Display.DEFAULT_DISPLAY, null, getCompatibilityInfo(),
                    getClassLoader());
        }
        return mResources;
    }
```

Suspicious that it's throwing an exception on trying to load this file? Something like 'no dex path found for'
`/data/app/com.ferg.awfulapp.debug-e9Hij-cppr0MAxscvSyG_g==/split_lib_resources_apk.apk`

I don't know where that's being caught, though, because it seems to continue on...

If I continue past there, inside of isFirebaseCrashlyticsEnabled, we call:
`CommonUtils.getBooleanResourceValue(context, "com.crashlytics.useFirebaseAppId", false))`

And that guy is getting a string value out as a boolean (the debugger died when I was trying to copy it out, but the parseInt failed). I think that one might be getting eaten and allowing startup to proceed, too, and it just eventually crashes on the preferences one I posted earlier.

**Comment by danieljennings** [comment]
Seeing something about people running into real Dex issues and they say to turn off Instant Run, so I tried that and now it's just skipping over that first exception right into the second. So it must be handled gracefully? I think that resource one might also not be real, either? I don't know but I don't see anything scary going on like I know is scary here.

These guys look like they're passing the right values in each time:
```
    public static final int pref_key_inline_youtube=0x7f10014b;
    public static final int pref_key_last_version_seen=0x7f10014c;
```

And I've verified it loads the preference fine during the first load, but it's downstream of calling `mPrefs.setPreference(Keys.LAST_VERSION_SEEN, versionCode)`, which sets that key to 10002, but also triggers us to re-get all of the preferences re `onSharedPreferenceChanged`, and that's when it blows up on the youtube one.

**Comment by danieljennings** [comment]
Uh, what? Something is fucky for sure, the IDE is like "yeah that's ...40 for sure" but at runtime it's "...39" which lines up with youtube...

![image](https://user-images.githubusercontent.com/582974/48986081-d570dd00-f0c4-11e8-8425-50cf7a1cd67f.png)

**Comment by Sereri** [comment]
Yeah, I'm pretty sure that happened the same way for me. I mean, I could swear I cleaned my build but I'm not going to check and just assume I did not actually do that.

Maybe we should add an empty secrets.xml to the repository then make it ignore changes. I'm pretty sure that's possible _somehow_

**Comment by baka-kaba** [comment]
Oh hey a chat thread

Yeah if you ever have issues it's a good idea to do ``Build > Clean`` and get that generated code outta there. Especially if you've done something like switched branches. I'm not sure if it's the caching or what, but I guess to keep things fast they sometimes leave the wrong stuff lying around

I think you can add a blank ``secrets.xml`` and the ``.gitignore`` will still ignore it when it comes to commits. We just need to make sure we have it backed up so we can replace it locally when the repo version appears and overwrites it. There's only a few of us using it so we just need to organise it
